# Generated by Django 5.2.7 on 2026-02-27 14:29

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome da gamificação ou conquista', max_length=150, verbose_name='Título')),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Quantidade de pontos concedidos', verbose_name='Pontos')),
            ],
            options={
                'verbose_name': 'Gamificação',
                'verbose_name_plural': 'Gamificações',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nome identificador da rede (ex: 'Campus Natal Central')", max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, help_text='Descrição opcional da rede', verbose_name='Descrição')),
                ('ip_addresses', models.TextField(help_text='IPs ou redes permitidas (um por linha). Exemplo: 192.168.1.0/24 ou 10.0.0.1', verbose_name='Endereços IP/Redes')),
                ('is_active', models.BooleanField(default=True, help_text='Desmarque para desativar temporariamente esta rede', verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TipoGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BDG', 'Badge'), ('TRF', 'Troféu'), ('MDL', 'Medalha')], max_length=3, verbose_name='Tipo')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='gamificacao/icones/', verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de gamificação',
                'verbose_name_plural': 'Tipos de gamificação',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='TrilhaGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Trilha de Entrada', max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, help_text='Descrição da trilha', verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('end_time', models.DateTimeField(verbose_name='Término')),
                ('is_enabled', models.BooleanField(default=True, help_text='Habilitar o registro de presença.', verbose_name='Habilitar?')),
                ('qr_timeout', models.IntegerField(default=0, help_text='Tempo de validade de cada QR Code para registro de presença (em segundos). Use "0" para desabilitar.', verbose_name='Timeout do QR Code (segundos)')),
                ('restrict_ip', models.BooleanField(default=False, help_text='Ativar restrição de acesso por endereço IP', verbose_name='Restringir por IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criação')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificação')),
                ('owners', models.ManyToManyField(related_name='owned_activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text="Tags para organizar as atividades (ex: 'Workshop 2024', 'Python')", through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('gamificacao', models.ForeignKey(blank=True, help_text='Gamificação concedida ao registrar presença nesta atividade.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='presente.gamificacao', verbose_name='Gamificação associada')),
                ('allowed_networks', models.ManyToManyField(blank=True, help_text='Selecione as redes que podem acessar esta atividade', to='presente.network', verbose_name='Redes permitidas')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='presente.trilhagamificacao', verbose_name='Trilha')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
            },
        ),
        migrations.AddField(
            model_name='gamificacao',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gamificacoes', to='presente.tipogamificacao', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tipogamificacao',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='presente.trilhagamificacao'),
        ),
        migrations.AddField(
            model_name='gamificacao',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacoes', to='presente.trilhagamificacao', verbose_name='Trilha'),
        ),
        migrations.CreateModel(
            name='UsuarioGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_concedida', models.DateTimeField(auto_now_add=True, verbose_name='Data concedida')),
                ('gamificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='presente.gamificacao', verbose_name='Gamificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Gamificação do usuário',
                'verbose_name_plural': 'Gamificações dos usuários',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_in_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP do usuário no momento do check-in', null=True, verbose_name='Endereço IP')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='presente.activity', verbose_name='Atividade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-checked_in_at'],
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.AddConstraint(
            model_name='tipogamificacao',
            constraint=models.UniqueConstraint(fields=('trilha', 'tipo'), name='unique_tipo_por_trilha'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariogamificacao',
            unique_together={('user', 'gamificacao')},
        ),
    ]
