# Generated by Django 5.2.7 on 2026-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0016_alter_activity_created_at_alter_activity_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrilhaGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trilha', models.CharField(help_text='Ex: Mestre da Informática, Jogador Iniciante, Jogador Profissional', max_length=100, unique=True, verbose_name='Nome da trilha')),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da trilha de gamificação', verbose_name='Descrição')),
                ('ativa', models.BooleanField(default=True, help_text='Indica se a trilha está ativa', verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
            ],
            options={
                'verbose_name': 'Trilha de Gamificação',
                'verbose_name_plural': 'Trilhas de Gamificação',
                'ordering': ['trilha'],
            },
        ),
    ]
