# Generated by Django 5.2.7 on 2026-02-18 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0017_trilhagamificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trilhagamificacao',
            options={'ordering': ['name'], 'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.RemoveField(
            model_name='trilhagamificacao',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='trilhagamificacao',
            name='criada_em',
        ),
        migrations.RemoveField(
            model_name='trilhagamificacao',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='trilhagamificacao',
            name='trilha',
        ),
        migrations.AddField(
            model_name='trilhagamificacao',
            name='name',
            field=models.CharField(default='Trilha de Entrada', max_length=100, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='TipoGamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BDG', 'Badge'), ('TRF', 'Troféu'), ('MDL', 'Medalha')], max_length=3, verbose_name='Tipo')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='gamificacao/icones/', verbose_name='Ícone')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='presente.trilhagamificacao')),
            ],
            options={
                'verbose_name': 'Tipo de gamificação',
                'verbose_name_plural': 'Tipos de gamificação',
                'ordering': ['tipo'],
                'constraints': [models.UniqueConstraint(fields=('trilha', 'tipo'), name='unique_tipo_por_trilha')],
            },
        ),
    ]
