# Generated by Django 5.2.7 on 2026-02-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0018_alter_trilhagamificacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhagamificacao',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição da trilha', verbose_name='Descrição'),
        ),
    ]
