# Generated by Django 5.2.7 on 2026-02-18 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0019_trilhagamificacao_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nome da gamificação ou conquista', max_length=150, verbose_name='Título')),
                ('pontos', models.PositiveIntegerField(default=0, help_text='Quantidade de pontos concedidos', verbose_name='Pontos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gamificacoes', to='presente.tipogamificacao', verbose_name='Tipo')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamificacoes', to='presente.trilhagamificacao', verbose_name='Trilha')),
            ],
            options={
                'verbose_name': 'Gamificação',
                'verbose_name_plural': 'Gamificações',
                'ordering': ['titulo'],
            },
        ),
    ]
