# Generated by Django 5.2.7 on 2026-02-22 00:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presente', '0021_usuariogamificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariogamificacao',
            options={'verbose_name': 'Gamificação do usuário', 'verbose_name_plural': 'Gamificações dos usuários'},
        ),
        migrations.AddField(
            model_name='usuariogamificacao',
            name='data_concedida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data concedida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariogamificacao',
            name='gamificacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='presente.gamificacao', verbose_name='Gamificação'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usuariogamificacao',
            unique_together={('user', 'gamificacao')},
        ),
    ]
